{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "databasus.fullname" . }}-backup-reader
  labels:
    {{- include "databasus.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "namespaces"]
    verbs: ["get", "list"]
{{- end }}
